#+TITLE: Ephesians
* 1
1. Paul, an apostle of the Anointed Jesus through the will of God, to the holy ones who are at Ephesus, and the faithful in the Anointed Jesus:
2. Grace to you all and peace from God our Father and the Lord Jesus the Anointed.

3. Blessed be the God and Father of our Lord Jesus the Anointed, who has blessed us with every spiritual blessing in the heavenly places in the Anointed,
4. even as he chose us in him before the foundation of the world, that we would be holy and without defect before him in love,
5. having marked us beforehand for adoption as children through Jesus the Anointed to himself, according to the good pleasure of his desire,
6. to the praise of the glory of his grace, by which he freely gave us favor in the Beloved.
7. In him we have our redemption through his blood, the forgiveness of our trespasses, according to the riches of his grace
8. which he made to abound toward us in all wisdom and prudence,
9. making known to us the mystery of his will, according to his good pleasure which he purposed in him
10. to an administration of the fullness of the seasons, to unite all things in the Anointed, the things in the heavens and the things on the earth, in him.
11. We were also assigned an inheritance in him, having been marked beforehand according to the purpose of him who is acting in all things after the counsel of his will,
12. to the end that we should be to the praise of his glory, we who had before hoped in the Anointed.
13. In him you all also, having heard the word of the truth, the good news of you all's salvation—in whom, having also believed, you all were sealed with the promised Holy Spirit,
14. who is a pledge of our inheritance, to the ransom of God’s own possession, to the praise of his glory.

15. Therefore I also, having heard of the faithfulness in the Lord Jesus which is among you all and the love toward all the holy ones,
16. don’t cease to give thanks for you all, making remembrance of you all in my prayers,
17. that the God of our Lord Jesus the Anointed, the Father of glory, may give to you all a spirit of wisdom and revelation in the knowledge of him,
18. having the eyes of you all's hearts enlightened, that you all may know what is the hope of his calling, and what are the riches of the glory of his inheritance in the holy ones,
19. and what is the exceeding greatness of his power toward us who believe, according to that activity of the strength of his might
20. which he operated in the Anointed when he raised him from the dead and made him to sit at his right hand in the heavenly places,
21. far above all rule, authority, power, dominion, and every name that is named, not only in this age, but also in that which is to come.
22. He put all things in subjection under his feet, and gave him to be head over all things for the assembly,
23. which is his body, the fullness of him who fills all in all.
* 2
1. You all were made alive while dead in transgressions and sins,
2. in which you all once walked according to the course of this world, according to the prince of the power of the air, the spirit who now operates in the children of disobedience.
3. We also all once lived among them in the lusts of our flesh, doing the desires of the flesh and of the mind, and were by nature children of wrath, even as the rest.
4. But God, being rich in mercy, for his great love with which he loved us,
5. even when we were dead through our trespasses, made us alive together with the Anointed—by grace you all have been saved—
6. and raised us up with him, and made us to sit with him in the heavenly places in the Anointed Jesus,
7. that in the coming ages he might show the exceeding riches of his grace in kindness toward us in the Anointed Jesus;
8. for by grace you all have been saved through his faithfulness, and that not of yourselves; it is the gift of God,
9. not of works, that no one would boast.
10. For we are his workmanship, created in the Anointed Jesus for good works, which God prepared before that we would walk in them.

11. Therefore remember that once you all, the nations in the flesh, who are called “uncircumcision” by that which is called “circumcision” (in the flesh, made by hands),
12. that you all were at that time without the Anointed, alienated from the commonwealth of Israel, and strangers from the covenants of the promise, having no hope and without God in the world.
13. But now in the Anointed Jesus you all who once were far off are made near in the blood of the Anointed.
14. For he is our peace, who made both one, and broke down the middle wall of separation,
15. having abolished in his flesh the hostility, the law of commandments contained in ordinances, that he might create in himself one new man of the two, making peace,
16. and might reconcile them both in one body to God through the cross, having killed the hostility through it.
17. He came and preached peace to you all who were far off and to those who were near.
18. For through him we both have our access in one Spirit to the Father.
19. So then you all are no longer strangers and foreigners, but you all are fellow citizens with the holy ones and of the household of God,
20. being built on the foundation of the apostles and prophets, the Anointed Jesus himself being the chief cornerstone;
21. in whom the whole building, fitted together, grows into a holy temple in the Lord;
22. in whom you all also are built together for a habitation of God in the Spirit.
* 3
1. For this cause I, Paul, am the prisoner of the Anointed Jesus on behalf of you all, the nations,
2. if it is so that you all have heard of the stewardship of the grace of God which was given me toward you all,
3. how that by revelation the mystery was made known to me, as I wrote before in few words,
4. by which, when you read, you can perceive my understanding in the mystery of the Anointed,
5. which in other generations was not made known to the children of men, as it has now been revealed to his holy apostles and prophets in the Spirit,
6. that the nations are fellow heirs and fellow members of the body, and fellow partakers of his promise in the Anointed Jesus through the good news,
7. of which I was made a servant according to the gift of that grace of God which was given me according to the activity of his power.
8. To me, the very least of all holy ones, was this grace given, to preach to the nations the unsearchable riches of the Anointed,
9. and to make all men see what is the stewardship of the mystery which for ages has been hidden in God, who created all things through Jesus the Anointed,
10. to the intent that now through the assembly the manifold wisdom of God might be made known to the principalities and the powers in the heavenly places,
11. according to the purpose of the ages which he accomplished in the Anointed Jesus our Lord.
12. In him we have boldness and access in confidence through his faithfulness.
13. Therefore I ask that you all may not lose heart at my troubles for you, which are you all's glory.

14. For this grace, I bow my knees to the Father of our Lord Jesus the Anointed,
15. from whom every family in heaven and on earth is named,
16. that he would grant you all, according to the riches of his glory, that you all may be strengthened with power through his Spirit in the inner person,
17. that the Anointed may dwell in you all's hearts through faithfulness, to the end that you all, being rooted and grounded in love,
18. may be strengthened to comprehend with all the holy ones what is the width and length and height and depth,
19. and to know the Anointed’s love which surpasses knowledge, that you all may be filled with all the fullness of God.

20. Now to him who is able to do exceedingly abundantly above all that we ask or think, according to the power that is active in us,
21. to him be the glory in the assembly and in the Anointed Jesus to all generations of the age of ages. Amen.
* 4
1. I therefore, the prisoner in the Lord, beg you all to walk worthily of the calling with which you all were called,
2. with all lowliness and gentleness, with patience, bearing with one another in love,
3. being eager to keep the unity of the Spirit in the bond of peace.
4. There is one body and one Spirit, even as you all also were called in one hope of you all's calling,
5. one Lord, one faith, one baptism,
6. one God and Father of all, who is over all and through all and in us all.
7. But to each one of us, the grace was given according to the measure of the gift of the Anointed.
8. Therefore he says,
#+BEGIN_VERSE
    “When he ascended on high,
      he led captivity captive,
      and gave gifts to people.”
#+END_VERSE
9. Now this, “He ascended”, what is it but that he also first descended into the lower parts of the earth?
10. He who descended is the one who also ascended far above all the heavens, that he might fill all things.

11. He gave some to be apostles; and some, prophets; and some, evangelists; and some, shepherds and teachers;
12. for the preparation of the holy ones, to the work of serving, to the building up of the body of the Anointed,
13. until we all attain to the unity of the faith and of the knowledge of the Son of God, to a full grown man, to the measure of the stature of the fullness of the Anointed,
14. that we may no longer be children, tossed back and forth and carried about with every wind of doctrine, by the trickery of men, in craftiness, after the wiles of error;
15. but speaking truth in love, we may grow up in all things into him who is the head, the Anointed,
16. from whom all the body, being fitted and knit together through that which every joint supplies, according to its activity in measure of each individual part, makes the body increase to the building up of itself in love.

17. This I say therefore, and testify in the Lord, that you all no longer walk as the rest of the nations also walk, in the futility of their mind,
18. being darkened in their understanding, alienated from the life of God because of the ignorance that is in them, because of the hardening of their hearts.
19. They, having become callous, gave themselves up to lust, to every unclean activity with greediness.
20. But you all didn’t learn the Anointed that way,
21. if indeed you heard him and were taught in him, even as truth is in Jesus:
22. that you put away, as concerning your former way of life, the old man that grows corrupt after the lusts of deceit,
23. and that you be renewed in the spirit of your mind,
24. and put on the new man, who in the likeness of God has been created in righteousness and holiness of truth.

25. Therefore, putting away falsehood, speak truth each one with his neighbor, for we are members of one another.
26. “Be angry, and don’t sin.” Don’t let the sun go down on your wrath,
27. and don’t give place to the slanderer.
28. Let him who stole steal no more; but rather let him labor, producing with his hands something that is good, that he may have something to give to him who has need.
29. Let no corrupt speech proceed out of your mouth, but only what is good for building others up as the need may be, that it may give grace to those who hear.
30. Don’t grieve the Holy Spirit of God, in whom you were sealed for the day of ransom.
31. Let all bitterness, temper, anger, outcry, and slander be put away from you, with all evil.
32. And be kind to one another, tender hearted, forgiving each other, just as God also in the Anointed forgave you all.
* 5
1. Become therefore imitators of God, as beloved children.
2. Walk in love, even as the Anointed also loved us and gave himself up for us, an offering and a sacrifice to God for a sweet-smelling fragrance.

3. But sexual immorality, and all uncleanness or greed, let it not even be mentioned among you all, as becomes holy ones;
4. nor filthiness, nor foolish talking, nor jesting, which are not appropriate, but rather giving of thanks.

5. Know this for sure, that no sexually immoral person, nor unclean person, nor greedy man (who is an idolater), has any inheritance in the Kingdom of the Anointed and God.

6. Let no one deceive you all with empty words, for because of these things the wrath of God comes on the children of disobedience.
7. Therefore don’t be partakers with them.
8. For you all were once darkness, but are now light in the Lord. Walk as children of light,
9. for the fruit of the Spirit is in all goodness and righteousness and truth,
10. proving what is well pleasing to the Lord.
11. Have no fellowship with the unfruitful deeds of darkness, still more reprove them.
12. For it is a shame even to speak of the things which are done by them in secret.
13. But all things, when they are reproved, are revealed by the light, for everything that reveals is light.
14. Therefore he says, “Awake, you who sleep, and arise from the dead, and the Anointed will shine on you.”

15. Therefore watch carefully how you walk, not as unwise, but as wise,
16. redeeming the season, because the days are evil.
17. Therefore, don’t be foolish, but understand what the will of the Lord is.
18. Don’t be drunken with wine, in which is dissipation, but be filled with the Spirit,
19. speaking to one another in psalms, hymns, and spiritual songs; singing and making melody in your heart to the Lord;
20. giving thanks always concerning all things in the name of our Lord Jesus the Anointed to the God even the Father;
21. subjecting you all's selves to one another in the fear of the Anointed.

22. Wives, be subject to your own husbands, as to the Lord.
23. For the husband is the head of the wife, as the Anointed also is the head of the assembly, being himself the savior of the body.
24. But as the assembly is subject to the Anointed, so let the wives also be to their own husbands in everything.

25. Husbands, love his own wives, even as the Anointed also loved the assembly and gave himself up for her,
26. that he might sanctify her, having cleansed her by the washing of water in the word,
27. that he might present the assembly to himself gloriously, not having spot or wrinkle or any such thing, but that she should be holy and without defect.
28. Even so husbands also ought to love their own wives as their own bodies. He who loves his own wife loves himself.
29. For no man ever hated his own flesh, but nourishes and cherishes it, even as the Lord also does the assembly,
30. because we are members of his body, of his flesh and bones.
31. “For this cause a man will leave his father and mother and will be joined to his wife. Then the two will become one flesh.”
32. This mystery is great, but I speak concerning the Anointed and the assembly.
33. Nevertheless each of you all must also love his own wife even as himself; and let the wife see that she respects her husband.
* 6
1. Children, obey you all's parents in the Lord, for this is right.
2. “Honor your father and mother,” which is the first commandment with a promise:
3. “that it may be well with you, and you may live long on the earth.”

4. You fathers, don’t provoke your children to wrath, but nurture them in the discipline and instruction of the Lord.

5. Slaves, be obedient to those who according to the flesh are you all's masters, with fear and trembling, in singleness of your heart, as to the Anointed,
6. not in the way of service only when eye service, as men pleasers, but as servants of the Anointed, doing the will of God from the heart,
7. with good will doing service as to the Lord and not to men,
8. knowing that whatever good thing each one does, he will receive the same good again from the Lord, whether he is bound or free.

9. You lords, do the same things to them, and give up threatening, knowing that he who is both their Lord and you all's is in heaven, and there is no partiality with him.

10. Finally, be strong in the Lord and in the strength of his might.
11. Put on the whole armor of God, that you may be able to stand against the wiles of the slanderer.
12. For our wrestling is not against flesh and blood, but against the principalities, against the powers, against the world’s rulers of the darkness of this age, and against the spiritual forces of wickedness in the heavenly places.
13. Therefore put on the whole armor of God, that you may be able to rise in the evil day, and having done all, to stand.
14. Stand therefore, having the belt of truth buckled about your waist, and having put on the breastplate of righteousness,
15. and having fitted your feet with the preparation of the good news of peace,
16. above all, taking up the shield of faithfulness, with which you will be able to quench all the fiery darts of the evil one.
17. And take the helmet of salvation, and the sword of the Spirit, which is the speech of God;
18. with all prayer and requests, praying at all times in the Spirit, and being watchful to this end in all perseverance and requests for all the holy ones.
19. Pray for me, that a word may be given to me in opening my mouth, to make known with boldness the mystery of the good news,
20. for which I am an ambassador in chains; that in it I may speak boldly, as I ought to speak.

21. But that you all also may know my affairs, how I am doing, Tychicus, the beloved brother and faithful servant in the Lord, will make known to you all things.
22. I have sent him to you for this very purpose, that you may know our state and that he may comfort your hearts.

23. Peace be to the brethren, and love with faith, from God the Father and the Lord Jesus the Anointed.
24. Grace be with all those who love our Lord Jesus the Anointed with incorruptible love. Amen.
